kube-state-metrics:
  image:
    repository: eddiezane/kube-state-metrics
    tag: v1.9.7

grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - grafana.simon-zengerling.de

    path: /

    tls: 
      - secretName: grafana-tls-secret
        hosts:
        - grafana.simon-zengerling.de
