apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: home-assistant
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./home-assistant
  prune: true
  sourceRef:
    kind: GitRepository
    name: smart-home-manifests
  validation: client