apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: zigbee
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./zigbee
  prune: true
  sourceRef:
    kind: GitRepository
    name: smart-home-manifests
  validation: client