apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
- monitoring-namespace.yaml
- prometheus-helm-source.yaml
- kube-prometheus-stack-helm-release.yaml
configMapGenerator:
  - name: kube-prometheus-values
    files:
      - values.yaml=kube-prometheus-values.yaml
configurations:
  - kustomizeconfig.yaml