apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
- monitoring-namespace.yaml
- prometheus-helm-source.yaml
- kube-prometheus-stack-helm-release.yaml
- nginx-dashboard.yaml
- raspberry-nodes-dashboard.yaml
# - flux-podmonitor.yaml
# - nginx-podmonitor.yaml
# - grafana-secret-sealed.yaml
configMapGenerator:
  - name: kube-prometheus-values
    files:
      - values.yaml=kube-prometheus-values.yaml
configurations:
  - kustomizeconfig.yaml