kind: PodMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: ingress-nginx-monitor
  labels:
    release: prometheus-stack
  namespace: monitoring
spec:
  podMetricsEndpoints:  
  - port: "metrics"
  namespaceSelector:
    matchNames:
      - ingress-nginx
  selector:
    matchLabels:
      prometheus: "true" 