---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: food-app-alert
  namespace: flux-system
spec:
  providerRef:
    name: food-app-provider
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: frontend-food-app
      namespace: flux-system