
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: food-app-provider
  namespace: flux-system
spec:
  type: github
  username: flux
  channel: general
  address: https://github.com/Sijoma/food-app
  secretRef:
    name: github-pat-notification