apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: whoogle
resources:
  - whoogle-ns.yaml
  - whoogle-helm-release.yaml
configMapGenerator:
  - name: whoogle-values
    files:
      - values.yaml=whoogle-values.yaml
configurations:
  - kustomizeconfig.yaml