HTTPS_ONLY: true

image:
  repository: benbusby/whoogle-search
  tag: buildx-experimental

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: search.simon-zengerling.de
      paths:
        - path: /
          pathType: Prefix

  tls:
    - secretName: whoogle-tls-secret
      hosts:
        - search.simon-zengerling.de