apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: whoogle
spec:
  interval: 5m
  chart:
    spec:
      chart: whoogle
      version: '1.3.0'
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: home
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: whoogle-values
  values: 
    replicaCount: 1