apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
resources:
  - postgres-ns.yaml
  - postgres-pv.yaml
  - postgres-helm-repo.yaml
  - postgres-helm-release.yaml
configMapGenerator:
  - name: postgres-values
    files:
      - values.yaml=postgres-values.yaml
configurations:
  - kustomizeconfig.yaml