apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: '10.3.x'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: storage
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: postgres-values
  values: 
    replicaCount: 1